use tower_lsp::lsp_types::{SemanticTokenModifier, SemanticTokenType};

// pub const TOKEN_TYPES_: [&str; 23] = [
//     "namespace",
//     "type",
//     "class",
//     "enum",
//     "interface",
//     "struct",
//     "typeParameter",
//     "parameter",
//     "variable",
//     "property",
//     "enumMember",
//     "event",
//     "function",
//     "method",
//     "macro",
//     "keyword",
//     "modifier",
//     "comment",
//     "string",
//     "number",
//     "regexp",
//     "operator",
//     "decorator",
// ];
//
// pub const TOKEN_MODIFIERS_: [&str; 10] = [
//     "declaration",
//     "definition",
//     "readonly",
//     "static",
//     "deprecated",
//     "abstract",
//     "async",
//     "modification",
//     "documentation",
//     "defaultLibrary",
// ];

pub const SEMANTIC_TOKEN_TYPES: [SemanticTokenType; 23] = [
    SemanticTokenType::NAMESPACE,
    SemanticTokenType::TYPE,
    SemanticTokenType::CLASS,
    SemanticTokenType::ENUM,
    SemanticTokenType::INTERFACE,
    SemanticTokenType::STRUCT,
    SemanticTokenType::TYPE_PARAMETER,
    SemanticTokenType::PARAMETER,
    SemanticTokenType::VARIABLE,
    SemanticTokenType::PROPERTY,
    SemanticTokenType::ENUM_MEMBER,
    SemanticTokenType::EVENT,
    SemanticTokenType::FUNCTION,
    SemanticTokenType::METHOD,
    SemanticTokenType::MACRO,
    SemanticTokenType::KEYWORD,
    SemanticTokenType::MODIFIER,
    SemanticTokenType::COMMENT,
    SemanticTokenType::STRING,
    SemanticTokenType::NUMBER,
    SemanticTokenType::REGEXP,
    SemanticTokenType::OPERATOR,
    SemanticTokenType::DECORATOR,
];

pub const SEMANTIC_TOKEN_MODIFIERS: [SemanticTokenModifier; 10] = [
    SemanticTokenModifier::DECLARATION,
    SemanticTokenModifier::DEFINITION,
    SemanticTokenModifier::READONLY,
    SemanticTokenModifier::STATIC,
    SemanticTokenModifier::DEPRECATED,
    SemanticTokenModifier::ABSTRACT,
    SemanticTokenModifier::ASYNC,
    SemanticTokenModifier::MODIFICATION,
    SemanticTokenModifier::DOCUMENTATION,
    SemanticTokenModifier::DEFAULT_LIBRARY,
];