pub const TOKEN_TYPES: [&str; 23] = [
    "namespace",
    "type",
    "class",
    "enum",
    "interface",
    "struct",
    "typeParameter",
    "parameter",
    "variable",
    "property",
    "enumMember",
    "event",
    "function",
    "method",
    "macro",
    "keyword",
    "modifier",
    "comment",
    "string",
    "number",
    "regexp",
    "operator",
    "decorator",
];

pub const TOKEN_MODIFIERS: [&str; 10] = [
    "declaration",
    "definition",
    "readonly",
    "static",
    "deprecated",
    "abstract",
    "async",
    "modification",
    "documentation",
    "defaultLibrary",
];
//
// pub const RSHTML_CAPTURE_NAMES: [&str; 15] = [
//     "operator",
//     "punctuation.special",
//     "punctuation.bracket",
//     "punctuation.delimiter",
//     "string",
//     "comment",
//     "operator",
//     "keyword",
//     "number",
//     "boolean",
//     "type",
//     "parameter",
//     "tag_open",
//     "tag_close",
//     "tag_end_open",
// ];
//
// pub const RSHTML_CAPTURE_NAMES_UNIQUE: [&'static str; 11] = [
//     "operator",
//     "punctuation.special",
//     "punctuation.bracket",
//     "punctuation.delimiter",
//     "string",
//     "comment",
//     "keyword",
//     "number",
//     "boolean",
//     "type",
//     "parameter",
// ];
//
// pub const TS_TOKEN_TYPES: [&'static str; 14] = [
//     "html",
//     "rust",
//     "operator",
//     "punctuation.special",
//     "punctuation.bracket",
//     "punctuation.delimiter",
//     "string",
//     "comment",
//     "operetor",
//     "keyword",
//     "number",
//     "boolean",
//     "type",
//     "parameter",
// ];
