name: Build and Upload to Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Upload Assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive_name: rshtml-analyzer-linux-x64.tar.gz
            binary_name: rshtml-analyzer
          - os: macos-latest
            target: x86_64-apple-darwin
            archive_name: rshtml-analyzer-macos-x64.tar.gz
            binary_name: rshtml-analyzer
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive_name: rshtml-analyzer-windows-x64.zip
            binary_name: rshtml-analyzer.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Package for Linux/macOS
        if: runner.os != 'Windows'
        run: tar -czvf ${{ matrix.archive_name }} -C target/${{ matrix.target }}/release ${{ matrix.binary_name }}

      - name: Package for Windows
        if: runner.os == 'Windows'
        run: Compress-Archive -Path target\${{ matrix.target }}\release\${{ matrix.binary_name }} -DestinationPath ${{ matrix.archive_name }}

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.archive_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
